name: xCaddy Builder with modules

on:
  [workflow_dispatch]
 
jobs:

  build:

    runs-on: ubuntu-latest
        
    steps:
    -   name: Checkout
        uses: actions/checkout@v4

    -   name: Login to GitHub Container Registry
        run: echo $password | docker login $registry -u $username --password-stdin
        env:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_PAT }}

    -   name: Build the caddy Docker image
        run: |
          docker build . --tag $registry/$image:$jobname
          docker run $registry/$image:$jobname
          docker push $registry/$image:$jobname  
        env:
            registry: ghcr.io
            image: ${{ github.repository }}
            jobname: ${{ github.job }}
    
